INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('user1', 'user1@example.com', '{noop}123');
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('user2', 'user2@example.com', '{noop}123');
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD) VALUES ('user3', 'user3@example.com', '{noop}123');

INSERT INTO TIPOS (NOMBRE, USER_ID) VALUES ('Blanco 1', 1);
INSERT INTO TIPOS (NOMBRE, USER_ID) VALUES ('Tinto 1', 1);

INSERT INTO TIPOS (NOMBRE, USER_ID) VALUES ('Blanco 2', 2);
INSERT INTO TIPOS (NOMBRE, USER_ID) VALUES ('Tinto 2', 2);

INSERT INTO TIPOS (NOMBRE, USER_ID) VALUES ('Blanco 2', 3);
INSERT INTO TIPOS (NOMBRE, USER_ID) VALUES ('Tinto 2', 3);


INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Rioja', 1);
INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Valduero', 1);
INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Frisante', 1);

INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Rioja', 2);
INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Valduero', 2);
INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Frisante', 2);

INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Rioja', 3);
INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Valduero', 3);
INSERT INTO ORIGINS(NOMBRE, USER_ID) VALUES ('Frisante', 3);


INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 1', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 1, 1, 1);
INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 2', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 1, 2, 1);
INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 3', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 2, 1, 1);

INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 1', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 3, 3, 2);
INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 2', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 3, 3, 2);
INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 3', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 4, 4, 2);

INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 1', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 5, 7, 3);
INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 2', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 5, 7, 3);
INSERT INTO WINES (NOMBRE, DESCRIPTION, QUANTITY, PURCHASE_PRICE, LOCATION, FROM_YEAR, RATING, TIPO_ID, ORIGIN_ID, USER_ID)
    VALUES ('Nombre 3', 'Muy rico', 5, 20.00, 'Nevera', 2003, 5, 6, 8, 3);


INSERT INTO PURCHASE(COUNT, WINE_ID, USER_ID) VALUES (5,1,1);
INSERT INTO PURCHASE(COUNT, WINE_ID, USER_ID) VALUES (5,2,1);

INSERT INTO PURCHASE(COUNT, WINE_ID, USER_ID) VALUES (4,4,2);
INSERT INTO PURCHASE(COUNT, WINE_ID, USER_ID) VALUES (3,5,2);

INSERT INTO PURCHASE(COUNT, WINE_ID, USER_ID) VALUES (2,7,3);
INSERT INTO PURCHASE(COUNT, WINE_ID, USER_ID) VALUES (3,8,3);