DROP TABLE IF EXISTS TABLEDEMO;
CREATE TABLE WINE (
    ID INTEGER IDENTITY PRIMARY KEY,
    QUANTITY INTEGER DEFAULT 0,
    NAME VARCHAR(255) NULL,
    PRICE FLOAT DEFAULT 0.0,
    LOCATION VARCHAR(255) NULL,
);